services:
  db:
    image: mysql:5.7
    container_name: mysql_tests_php
    ports:
     - "3306:3306"
     - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testes_php
    networks:
      dbToTests:
        ipv4_address: 182.20.0.5
networks:
  dbToTests:
    driver: bridge
    ipam:
      config:
        - subnet: 182.20.0.0/16